# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

stages:
- gitlab-test
- yaml-lint
- jinja2-lint
- ansible-lint
- molecule-test

variables:
  PIPELINE_SCENARIO_NAME: "cicd-debian-11"

###############################################################################
#################### actions
###############################################################################

# To start, we need to lint role's files with a YML vision
# Because if one of the files doesn't respect YML conventions,
# we dont need to test rest of the pipeline
.yaml_lint: &yaml_lint
  stage: yaml-lint
  image: $NEXUS_ADDRESS/$DOCKER_IMAGE_YAML_LINT
  before_script:
    # Fix weird ansible bug: https://github.com/trailofbits/algo/issues/1637
    # This probably happens due to gitlab-runner mounting the git repo into the container
    - "chmod o-w ."
  script:
    - yamllint -c ./.yamllint $path # Here mains files
  allow_failure: false
  retry: 2

# Then we need to lint on role's files with a JINJA2 vision
# Because if one of the templates files doesn't respect JINJA2 conventions,
# we dont need to test rest of the pipeline
.jinja2_lint: &jinja2_lint
  stage: jinja2-lint
  image: $NEXUS_ADDRESS/$DOCKER_IMAGE_JINJA_LINT
  before_script:
    # Fix weird ansible bug: https://github.com/trailofbits/algo/issues/1637
    # This probably happens due to gitlab-runner mounting the git repo into the container
    - "chmod o-w ."
  script:
    - "j2lint ./templates/*.j2 --ignore S3 S7"
  allow_failure: false
  retry: 2

.ansible_lint: &ansible_lint
  stage: ansible-lint
  image: $NEXUS_ADDRESS/$DOCKER_IMAGE_ANSIBLE_LINT
  before_script:
    # Fix weird ansible bug: https://github.com/trailofbits/algo/issues/1637
    # This probably happens due to gitlab-runner mounting the git repo into the container
    - "chmod o-w ."
  script:
    - ansible-lint --config=./.ansible-lint --exclude molecule --exclude tests ./*
  allow_failure: false
  retry: 2

.molecule_test: &molecule_test
  stage: molecule-test
  image: $NEXUS_ADDRESS/$DOCKER_IMAGE_DOCKER_MOLECULE
  variables:
    PY_COLORS: '1'
    ANSIBLE_FORCE_COLOR: '1'
  before_script:
    - "docker login -u \"$NEXUS_REPOS_USERNAME\" -p \"$NEXUS_REPOS_PASSWORD\" http://$NEXUS_ADDRESS"
    - "python3 -m compileall /usr/lib/python3 -qq"
    - "cp ./.ansible.cfg /root/.ansible.cfg"
    # Fix weird ansible bug: https://github.com/trailofbits/algo/issues/1637
    # This probably happens due to gitlab-runner mounting the git repo into the container
    - "chmod o-w ."
    - "[ -f \"./molecule/$PIPELINE_SCENARIO_NAME/requirements.yml\" ] && ansible-galaxy install -r ./molecule/$PIPELINE_SCENARIO_NAME/requirements.yml --roles-path=./molecule/$PIPELINE_SCENARIO_NAME/roles"
  script:
    - "molecule test --scenario-name $PIPELINE_SCENARIO_NAME"
  allow_failure: false
  retry: 2

###############################################################################
#################### CI JOBS
###############################################################################

############################################
#### gitlab-test
############################################

# As a GitLab ci, we use the default template :)
sast:
  stage: gitlab-test
include:
- template: Security/SAST.gitlab-ci.yml
  allow_failure: false

############################################
#### yaml-lint
############################################

yaml_lint_role:
  <<: *yaml_lint
  variables:
    path: "./*/*.yml"

yaml_lint_molecule:
  <<: *yaml_lint
  variables:
    path: "./molecule/*/*.yml"

yaml_lint_inventories:
  <<: *yaml_lint
  variables:
    path: "./tests/inventory/hosts.yml ./tests/inventory/*/*.yml"

yaml_lint_extra_vars:
  <<: *yaml_lint
  variables:
    path: "./tests/certs/main.yml ./tests/tower/tower.yml"

#############################################
##### jinja2-lint
#############################################

jinja2_lint_templates:
  <<: *jinja2_lint

############################################
#### ansible-lint
############################################

ansible_lint:
  <<: *ansible_lint
  needs:
    - "yaml_lint_role"
    - "yaml_lint_molecule"
    - "yaml_lint_inventories"
    - "yaml_lint_extra_vars"
    - "jinja2_lint_templates"

############################################
#### moelcule test
############################################

molecule_test:
  <<: *molecule_test
  needs:
    - "ansible_lint"
